### ISSUE TITLE
Hi, i think if you don‘t want to share your code，you don't have to just miss something, it's easy to cause misunderstandings. It leads to a lot of time wasted when reproducing your code, thank you

### ISSUE THREAD

**Issue by shenyewei** [jaehong31/RACCooN#4]

**Comment by BhJia** [comment]
hello, can you leave your contact information for further communication? I just met some problems reproducing the code. Thanks!

**Comment by AaANNYYAaA** [comment]
@shenyewei hello, can you leave your contact information for further communication? I just met some problems reproducing the code. Thanks!

**Comment by shenyewei** [comment]
my email is 2056@mail.nwpu.edu.cn. Unfortunately, I have been reproducing this paper recently, but have not yet succeeded.

**Comment by jaehong31** [comment]
We appreciate your patience with the delay, and thank you for your interest in our work! We'll be uploading the full repo soon within October.
